### ISSUE TITLE
Celestia testnet explorer tracker

### ISSUE THREAD

**Issue by rach-id** [celestiaorg/big-dipper-2.0-cosmos#16]
This will track the remaining issues to be handled before testnet deployment:

- [x] https://github.com/celestiaorg/big-dipper-2.0-cosmos/issues/5
- [x] https://github.com/celestiaorg/big-dipper-2.0-cosmos/issues/15
- [x] https://github.com/celestiaorg/big-dipper-2.0-cosmos/issues/17
- [x] https://github.com/celestiaorg/bdjuno/issues/7
- [x] https://github.com/celestiaorg/bdjuno/issues/12
- [x] https://github.com/celestiaorg/juno/issues/4
- [x] https://github.com/celestiaorg/juno/issues/5

#### Stretch goals

- [ ] https://github.com/celestiaorg/big-dipper-2.0-cosmos/issues/14
- [ ] https://github.com/celestiaorg/big-dipper-2.0-cosmos/issues/13
- [ ] https://github.com/celestiaorg/big-dipper-2.0-cosmos/issues/6

**Comment by lzrscg** [comment]
Progress update:
- Made progress setting up infrastructure on AWS
- [Juno upstream pulled](https://github.com/celestiaorg/juno/issues/4#issuecomment-1132451420)
- [Juno cosmos-sdk version update, but bdjuno has issues](https://github.com/celestiaorg/juno/issues/5#issuecomment-1132485982)
- [Bdjuno upstream pulled](https://github.com/celestiaorg/bdjuno/issues/12#issuecomment-1132487588)

**Comment by lzrscg** [comment]
Current status
* [x]  [Fix testnet/mainnet config to reflect the correct `celes`/`uceles` units #5](https://github.com/celestiaorg/big-dipper-2.0-cosmos/issues/5)
* [x]  [Pull upstream and update the explorer #15](https://github.com/celestiaorg/big-dipper-2.0-cosmos/issues/15)
* [x]  [Rename PayForMessage to PayForData #17](https://github.com/celestiaorg/big-dipper-2.0-cosmos/issues/17)
* [x]  [Fix testnet/mainnet config to reflect the correct `celes`/`uceles` units bdjuno#7](https://github.com/celestiaorg/bdjuno/issues/7)
* [x]  [Pull upstream changes bdjuno#12](https://github.com/celestiaorg/bdjuno/issues/12)
* [x]  [Pull upstream changes juno#4](https://github.com/celestiaorg/juno/issues/4)
* [x]  [Depend on the latest version of Cosmos-SDK juno#5](https://github.com/celestiaorg/juno/issues/5)

**Comment by rach-id** [comment]
Great job :tada:

**Comment by rach-id** [comment]
Can you please  open PRs to our repos containing the changes ?

**Comment by lzrscg** [comment]
@SweeXordious I definitely will, but I haven't fully tested and there still are likely some issues. I will do that once I can confirm everything is polished and ready

**Comment by lzrscg** [comment]
ok everything is complete. next steps (in order)
1. deploy everything and find/fix bugs
2. contribute changes upstream
3. set up staking ui
4. try for stretch goals

**Comment by rach-id** [comment]
Sounds awesome. Thanks a lot for your help :D
